language: python
python:
- '3.6'
branches:
  only:
  - master
install:
- python setup.py -q install
- pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=ppmutils --cover-inclusive --cover-html
after_success:
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- pip install python-semantic-release
- semantic-release publish