# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install
      run: |
        python -m pip install --upgrade pip twine
        python setup.py -q install
        pip install -r requirements-test.txt
    - name: Lint
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        python setup.py test
    - uses: codfish/semantic-release-action@master
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update package version file
      if: steps.semantic.outputs.new-release-published == 'true'
      env:
        RELEASE_VERSION: steps.semantic.outputs.release-version
      run: |
        sed -ie "s/^__version__.*/__version__ = '$RELEASE_VERSION'/g" ppmutils/__init__.py
        git config --global user.name "semantic-release (via Github Actions)"
        git config --global user.email "semantic-release@github"
        git add ppmutils/__init__.py && git commit -m "Actions: Updating package version file"
    - name: Package and Deploy
      if: steps.semantic.outputs.new-release-published == 'true'
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --non-interactive -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" dist/*